### ISSUE TITLE
need favicons

### ISSUE THREAD

**Issue by hirefrank** [hirefrank/hellonellwyn.com#2]
@nellwyn what do you want to use?

For @hirefrank implementation:
*Favicon*
Use [RealFaviconGenerator](https://realfavicongenerator.net/) to generate these files, put them into your site's static folder:

android-chrome-192x192.png
android-chrome-512x512.png
apple-touch-icon.png
favicon-16x16.png
favicon-32x32.png
favicon.ico
mstile-150x150.png
safari-pinned-tab.svg
site.webmanifest

**Comment by nellwyn** [comment]
raccoon emoji duh

**Comment by hirefrank** [comment]
done: https://github.com/hirefrank/hellonellwyn.com/commit/431bcd7b7388e5925327d5556977bdbc110c435e
